// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/walrusyu/gocamp007/week4/internal/biz"
	"github.com/walrusyu/gocamp007/week4/internal/data"
	"github.com/walrusyu/gocamp007/week4/internal/service"
)

// Injectors from wire.go:

func InitUserServer() *service.Server {
	userRepo := data.NewUserRepo()
	userBiz := biz.NewUserBiz(userRepo)
	server := service.NewServer(userBiz)
	return server
}
